[ci skip] uhh thanks cgpt hopefully this does work :laughing:

diff --git a/tmp/nuts-cc b/tmp/nuts-cc
--- a/tmp/nuts-cc
+++ b/tmp/nuts-cc
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #############################################################################################################################################################################
 #   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
@@ -22,6 +22,9 @@
 #    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
 #############################################################################################################################################################################
 
+
+# -- Exit on errors.
+
 set -xe
 
 
@@ -32,13 +35,24 @@ TOOL_SHRT_NAME="nuts-cc"
 
 # -- Print informative messages to stdin.
 
-puts-info () { printf "$TOOL_SHRT_NAME: \e[34mInfo:\e[0m %b\n\n" "$*"; }
+puts_info() {
+  printf "%s: \e[34mInfo:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print success messages to stdin.
 
-puts-success () { printf "$TOOL_SHRT_NAME: \e[32mSuccess:\e[0m %b\n\n" "$*"; }
+puts_success() {
+  printf "%s: \e[32mSuccess:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
+
+# -- Display an error when no flag is used.
+
+error () {
+  puts_error "$TOOL_SHRT_NAME: \e[31mError:\e[0m: $*" >&2
+  exit 1
+}
 
 #   ====== START ======
 
@@ -61,16 +75,16 @@ while IFS= read -r ITEM; do
 done < "$FILE_LIST"
 
 
-puts-success "Success! Cleanup complete, continuing..."
+puts_success "Success! Cleanup complete, continuing..."
 
 
 # -- Link kernel image to newer kernel
 
-puts-info "Preparing to boot new kernel and initram, continuing..."
+puts_info "Preparing to boot new kernel and initram, continuing..."
 
 ln -svf "$(echo /boot/vmlinuz* | tr ' ' '\n' | tail -n 1)" /vmlinuz
 ln -svf "$(echo /boot/initrd* | tr ' ' '\n' | tail -n 1)" /initrd.img
 
-puts-success "Success! Ready to use newer kernel, continuing..."
+puts_success "Success! Ready to use newer kernel, continuing..."
 
 #   ====== END ======
diff --git a/usr/bin/nuts b/usr/bin/nuts
--- a/usr/bin/nuts
+++ b/usr/bin/nuts
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #############################################################################################################################################################################
 #   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
@@ -40,27 +40,41 @@ FECHA=$(date +%Y)
 
 # -- Print informative messages to stdin.
 
-puts-info () { printf "$TOOL_SHRT_NAME: \e[34mInfo:\e[0m %b\n\n" "$*"; }
+puts_info() {
+  printf "%s: \e[34mInfo:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print success messages to stdin.
 
-puts-success () { printf "$TOOL_SHRT_NAME: \e[32mSuccess:\e[0m %b\n\n" "$*"; }
+puts_success() {
+  printf "%s: \e[32mSuccess:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print error messages to stdin.
 
-puts-error () { printf "$TOOL_SHRT_NAME: \e[31mError:\e[0m %b\n\n" "$*"; }
+puts_error() {
+  printf "%s: \e[31mError:\e[0m %b\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print messages or text using multiple lines.
 
-puts-text () { printf "%b\n" "$@" >&2; }
+print_message() {
+    local message="${1:-}"
+    local output_stream="${2:-2}"
+
+    printf "%b\n" "$message" >&"$output_stream"
+}
 
 
 # -- Display an error when no flag is used.
 
-error () { printf "$TOOL_SHRT_NAME: \e[31mError:\e[0m %b\n\n" "$*" >&2; exit 1; }
+error () {
+  puts_error "$TOOL_SHRT_NAME: \e[31mError:\e[0m: $*" >&2
+  exit 1
+}
 
 
 # -- Define the path of the nuts configuration file.
@@ -72,10 +86,10 @@ CONFIG_FILE="/etc/nuts.conf"
 # -- Include fix for SC1090 – ShellCheck.
 
 if [[ ! -f $CONFIG_FILE ]]; then
-    puts-error "$TOOL_NAME configuration file not found!, quitting." 2>&1
+    puts_error "$TOOL_NAME configuration file not found!, quitting." 2>&1
     exit 1
 else
-	puts-success "Success! $TOOL_NAME configuration file found, continuing..."
+	puts_success "Success! $TOOL_NAME configuration file found, continuing..."
 	# shellcheck source=/dev/null
 	. "$CONFIG_FILE"
 fi
@@ -85,36 +99,67 @@ fi
 # -- Exit if not running as root.
 
 if [ "$EUID" -ne 0 ]; then
-	puts-error "$TOOL_NAME is not running as root, quitting."
-	exit 1
+    puts_error "%s is not running as root, quitting.\n" "$TOOL_NAME"
+    exit 1
 else
-	puts-info "$TOOL_NAME is running as root, continuing..."
-	ROOT="sudo"
+    puts_info "%s is running as root, continuing...\n" "$TOOL_NAME"
+    ROOT=("sudo")
 fi
+
 
 
 # -- Functions.
 
-dl_file () { axel -q -o /tmp -n 10 "$@"; }
-overlay_ch () { $ROOT overlayroot-chroot "$@"; }
+dl_file() {
+    local FILE_URL="$1"
+    local FILE_NAME
+	FILE_NAME="$(basename "$FILE_URL")"
+    local FILE_PATH="/tmp/$FILE_NAME"
+
+    if [ -f "$FILE_PATH" ]; then
+        rm "$FILE_PATH"
+    fi
+
+    if ! command -v axel >/dev/null 2>&1; then
+        return 1
+    fi
+
+    if ! curl --output /dev/null --silent --head --fail "$FILE_URL"; then
+        return 1
+    fi
+
+    axel -o "/tmp" -n 10 "$FILE_URL"
+
+    if [ $? -ne 0 ]; then
+        return 1
+    fi
+}
+
+overlay_ch() {
+    local ROOT=("sudo" "overlayroot-chroot" "$@")
+
+    if ! command -v "${ROOT[0]}" >/dev/null 2>&1; then
+        printf "Error: '%s' command not found. Please make sure it's installed and try again.\n" "${ROOT[0]}"
+        return 1
+    fi
+
+    "${ROOT[@]}"
+}
 
 
 # -- Use a log file.
 # -- Everything below will go to the file nuts.log.
 
-$ROOT touch "$NUTS_LOG"
-
-if [[ ! -f $NUTS_LOG ]]; then
-	puts-info "Creating $TOOL_NAME log file, continuing..."
-	touch "$NUTS_LOG"
+if [ -f "$NUTS_LOG" ]; then
+	puts_info "$TOOL_NAME log file found, skipping..."
 else
-	puts-info "$TOOL_NAME log file found, skipping..."
+	puts_info "Unable to locate $TOOL_NAME log file."
 fi
 
 
 # -- Variables.
 
-CURRENT_DIST=$(tail /etc/os-release | grep "VERSION_CODENAME=*" | rev | cut -d '=' -f 1 | rev)
+CURRENT_DIST=$(awk -F'=' '/VERSION_CODENAME/{print $NF}' /etc/os-release)
 TARGET_DIST="nitrux"
 
 
@@ -124,7 +169,7 @@ TARGET_DIST="nitrux"
 
 for cmd; do
 	case "$cmd" in
-		( -h | --help ) puts-text \
+		( -h | --help ) print_message \
 			"$TOOL_NAME" \
 			"" \
 			"Description:" \
@@ -152,7 +197,7 @@ for cmd; do
 
 			exit;;
 
-		( -v | --version )  puts-text \
+		( -v | --version )  print_message \
 			"$TOOL_NAME — version: $TOOL_VERSION." \
 			"" \
 			"The license used for this file and its contents is: BSD-3-Clause." \
@@ -183,9 +228,9 @@ done
 			# -- Exit if value is not 'nitrux'.
 
 			if [ "$CURRENT_DIST" == "$TARGET_DIST" ]; then
-				puts-success "Success! This utility is running in ${TARGET_DIST^n}, continuing..."
+				puts_success "This utility is running in ${TARGET_DIST^}. Continuing..."
 			else
-				puts-error "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^n}, and using this utility in ${CURRENT_DIST^} will break it and not work at all. Quitting."
+				puts_error "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^}. Using this utility in ${CURRENT_DIST^} will break it and not work at all. Quitting."
 				exit 1
 			fi
 
@@ -194,9 +239,9 @@ done
 			# -- Exit if connection test fails.
 
 			if ping -q -c 1 -W 1 nxos.org >/dev/null; then
-				puts-success "Success! This computer can reach the Internet, continuing..."
+				puts_success "This computer can reach the Internet. Continuing..."
 			else
-				puts-error "This computer can't reach the Internet, quitting."
+				puts_error "This computer cannot reach the Internet. Quitting."
 				exit 1
 			fi
 
@@ -208,10 +253,10 @@ done
 			# -- Exit if it doesn't.
 
 			if [ ! -f "/installed_pkgs_end.txt" ]; then
-				puts-error "Build list not found, quitting."
+				puts_error "Build list not found. Quitting."
 				exit 1
 			else
-				puts-info "Build list found, continuing..."
+				puts_info "Build list found. Continuing..."
 			fi
 
 
@@ -219,15 +264,17 @@ done
 			# -- This file is always downloaded to a temporary directory, as there's no reason to keep it.
 			# -- Overwrite the file if it already exists.
 
-			if [ ! -f "/tmp/nuts-query.info" ]; then
-				puts-info "Can't find nuts-query.info, downloading..."
-				dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-query.info
+			INFO_FILE="/tmp/nuts-query.info"
+			REMOTE_URL="https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-query.info"
+
+			if [ ! -f "$INFO_FILE" ]; then
+				puts_info "Can't find nuts-query.info, downloading..."
 			else
-				puts-info "Found nuts-query.info, overwriting..."
-				rm -r \
-					/tmp/nuts-query.info
-				dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-query.info
+				puts_info "Found nuts-query.info, overwriting..."
+				rm -f "$INFO_FILE"
 			fi
+
+			dl_file "$REMOTE_URL" "$INFO_FILE"
 
 
 			# -- Make the comparison.
@@ -235,14 +282,14 @@ done
 			# -- If the checksum matches, exit because the root is already current.
 			# -- If the checksum doesn't match, then continue because the root is out of date or the list differs from the value in the query file.
 
-			LOCAL_SUM="$(md5sum /installed_pkgs_end.txt | cut -c -32)"
-			REMOTE_SUM="$(tail /tmp/nuts-query.info | grep rootlistsum= | cut -c -44 | rev | cut -c -32 | rev)"
+			LOCAL_SUM=$(md5sum /installed_pkgs_end.txt | cut -c -32)
+			REMOTE_SUM=$(tail /tmp/nuts-query.info | grep rootlistsum= | cut -c -44 | rev | cut -c -32 | rev)
 
 			if [ "$LOCAL_SUM" == "$REMOTE_SUM" ]; then
-				puts-info "The current installation of ${TARGET_DIST^n} is up to date."
+				puts_info "The current installation of ${TARGET_DIST^} is up to date."
 				exit 0
 			else
-				puts-info "Preparing to update ${TARGET_DIST^n}, continuing..."
+				puts_info "Preparing to update ${TARGET_DIST^}, continuing..."
 			fi
 
 
@@ -259,11 +306,13 @@ done
 			# -- After using overlay_ch, it's essential to remember that **EVERY COMMAND IS RUNNING AS ROOT AND ON THE LOWER DIRECTORY OF THE OVERLAY**.
 
 
-			if [ ! -f "/usr/sbin/overlayroot-chroot" ]; then
-				puts-error "Can't find overlayroot, quitting."
+			OVERLAYROOT="/usr/sbin/overlayroot-chroot"
+
+			if [ ! -f "$OVERLAYROOT" ]; then
+				puts_error "Can't find overlayroot, quitting."
 				exit 1
 			else
-				puts-info "Found overlayroot, continuing..."
+				puts_info "Found overlayroot, continuing..."
 			fi
 
 
@@ -281,7 +330,7 @@ done
 
 			# -- After running rsync reboot the device.
 
-			puts-info "Time to reboot. Bye."
+			puts_info "Time to reboot. Bye."
 
 			shift;;
 
@@ -309,7 +358,7 @@ done
 
 			# -- After running rsync reboot the device.
 
-			puts-info "Time to reboot. Bye."
+			puts_info "Time to reboot. Bye."
 
 			shift;;
 	esac
diff --git a/usr/bin/nuts-crr b/usr/bin/nuts-crr
--- a/usr/bin/nuts-crr
+++ b/usr/bin/nuts-crr
@@ -1,10 +1,9 @@
-#! /bin/bash
+#!/bin/bash
 
 #############################################################################################################################################################################
 #   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
 #                                                                                                                                                                           #
 #   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
-#   Copyright <2023> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                                 #
 #                                                                                                                                                                           #
 #   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
 #                                                                                                                                                                           #
@@ -32,22 +31,27 @@ set -xe
 # -- Set program name and version.
 
 TOOL_NAME="Nitrux Update System Tool"
-TOOL_SHRT_NAME="nuts"
 
 
 # -- Print informative messages to stdin.
 
-puts-info () { printf "$TOOL_SHRT_NAME: \e[34mInfo:\e[0m %b\n\n" "$*"; }
+puts_info() {
+  printf "%s: \e[34mInfo:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print success messages to stdin.
 
-puts-success () { printf "$TOOL_SHRT_NAME: \e[32mSuccess:\e[0m %b\n\n" "$*"; }
+puts_success() {
+  printf "%s: \e[32mSuccess:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print error messages to stdin.
 
-puts-error () { printf "$TOOL_SHRT_NAME: \e[31mError:\e[0m %b\n\n" "$*"; }
+puts_error() {
+  printf "%s: \e[31mError:\e[0m %b\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Define the path of the nuts configuration file.
@@ -59,10 +63,10 @@ CONFIG_FILE="/etc/nuts.conf"
 # -- Include fix for SC1090 – ShellCheck.
 
 if [[ ! -f $CONFIG_FILE ]]; then
-    puts-error "$TOOL_NAME configuration file not found!, quitting." 2>&1
+    puts_error "$TOOL_NAME configuration file not found!, quitting." 2>&1
     exit 1
 else
-	puts-success "Success! $TOOL_NAME configuration file found, continuing..."
+	puts_success "Success! $TOOL_NAME configuration file found, continuing..."
 	# shellcheck source=/dev/null
 	. "$CONFIG_FILE"
 fi
@@ -70,7 +74,7 @@ fi
 
 # -- Variables.
 
-CURRENT_DIST=$(tail /etc/os-release | grep "VERSION_CODENAME=*" | rev | cut -d '=' -f 1 | rev)
+CURRENT_DIST=$(awk -F'=' '/VERSION_CODENAME/{print $NF}' /etc/os-release)
 
 
 # -- Mount the devices filesystem.
@@ -102,24 +106,24 @@ done
 # -- Create working directories in /home since this partition will likely have more space than the root partition, as set in our custom partition layout and the instructions on the website.
 
 if [[ ! -d "$NUTS_DIR_DLS" ]] && [[ ! -d "$NUTS_DIR_ISO" ]] && [[ ! -d "$NUTS_DIR_SQS" ]] && [[ ! -d "$NUTS_DIR_BAK" ]]; then
-	puts-info "Creating working directories, continuing..."
+	puts_info "Creating working directories, continuing..."
 	mkdir -p /home/.nuts/{backup,downloads,iso,squashfs}
 else
-	puts-info "Working directories exist, skipping..."
+	puts_info "Working directories exist, skipping..."
 fi
 
 
 # -- Verify the checksum of the backup file with the generated checksum file.
 # -- Exit if checksum doesn't match.
 
-BACKUP_SUM="$(md5sum "$(echo "$NUTS_DIR_BAK"/nuts-backup-*.squashfs | tr ' ' '\n' | tail -n 1)" | cut -c -32)"
-GEN_BAK_SUM="$(tail "$NUTS_DIR_BAK"/nuts-backup.md5sum | cut -c -32)"
+BACKUP_SUM=$(md5sum "$(echo "$NUTS_DIR_BAK"/nuts-backup-*.squashfs | tr ' ' '\n' | tail -n 1)" | cut -c -32)
+GEN_BAK_SUM=$(tail "$NUTS_DIR_BAK"/nuts-backup.md5sum | cut -c -32)
 
 if [[ "$BACKUP_SUM" == "$GEN_BAK_SUM" ]]; then
-	puts-info "Backup checksum matches, continuing..."
+    puts_info "Backup checksum matches, continuing..."
 else
-	puts-error "Backup checksum does not match, quitting."
-	exit 1
+    puts_error "Backup checksum does not match, quitting."
+    exit 1
 fi
 
 
@@ -131,7 +135,7 @@ mount "$(echo "$NUTS_DIR_BAK"/nuts-backup-*.squashfs | tr ' ' '\n' | tail -n 1)"
 
 # -- Now comes the good part; proceed with running rsync and restore the backup.
 
-puts-info "Restoring backup of ${CURRENT_DIST^n}, continuing..."
+puts_info "Restoring backup of ${CURRENT_DIST^n}, continuing..."
 
 dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/rsync-exclude.list
 
@@ -144,7 +148,7 @@ eval "$RSYNC_COMMAND"
 
 sync
 
-puts-success "Success! Backup has been restored."
+puts_success "Success! Backup has been restored."
 
 
 # -- Unmount the SquashFS.
diff --git a/usr/bin/nuts-cru b/usr/bin/nuts-cru
--- a/usr/bin/nuts-cru
+++ b/usr/bin/nuts-cru
@@ -1,10 +1,9 @@
-#! /bin/bash
+#!/bin/bash
 
 #############################################################################################################################################################################
 #   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
 #                                                                                                                                                                           #
 #   Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
-#   Copyright <2023> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                                 #
 #                                                                                                                                                                           #
 #   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
 #                                                                                                                                                                           #
@@ -37,17 +36,41 @@ TOOL_SHRT_NAME="nuts"
 
 # -- Print informative messages to stdin.
 
-puts-info () { printf "$TOOL_SHRT_NAME: \e[34mInfo:\e[0m %b\n\n" "$*"; }
+puts_info() {
+  printf "%s: \e[34mInfo:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print success messages to stdin.
 
-puts-success () { printf "$TOOL_SHRT_NAME: \e[32mSuccess:\e[0m %b\n\n" "$*"; }
+puts_success() {
+  printf "%s: \e[32mSuccess:\e[0m %s\n\n" "$TOOL_NAME" "$*"
+}
 
 
 # -- Print error messages to stdin.
 
-puts-error () { printf "$TOOL_SHRT_NAME: \e[31mError:\e[0m %b\n\n" "$*"; }
+puts_error() {
+  printf "%s: \e[31mError:\e[0m %b\n\n" "$TOOL_NAME" "$*"
+}
+
+
+# -- Print messages or text using multiple lines.
+
+print_message() {
+    local message="${1:-}"
+    local output_stream="${2:-2}"
+
+    printf "%b\n" "$message" >&"$output_stream"
+}
+
+
+# -- Display an error when no flag is used.
+
+error () {
+  puts_error "$TOOL_SHRT_NAME: \e[31mError:\e[0m: $*" >&2
+  exit 1
+}
 
 
 # -- Define the path of the nuts configuration file.
@@ -59,10 +82,10 @@ CONFIG_FILE="/etc/nuts.conf"
 # -- Include fix for SC1090 – ShellCheck.
 
 if [[ ! -f $CONFIG_FILE ]]; then
-    puts-error "$TOOL_NAME configuration file not found!, quitting." 2>&1
+    puts_error "$TOOL_NAME configuration file not found!, quitting." 2>&1
     exit 1
 else
-	puts-success "Success! $TOOL_NAME configuration file found, continuing..."
+	puts_success "Success! $TOOL_NAME configuration file found, continuing..."
 	# shellcheck source=/dev/null
 	. "$CONFIG_FILE"
 fi
@@ -70,13 +93,49 @@ fi
 
 # -- Variables.
 
-CURRENT_DIST=$(tail /etc/os-release | grep "VERSION_CODENAME=*" | rev | cut -d '=' -f 1 | rev)
+CURRENT_DIST=$(awk -F'=' '/VERSION_CODENAME/{print $NF}' /etc/os-release)
 
 
 # -- Functions.
 
-dl_file () { axel -o /tmp -n 10 "$@"; }
-bak_cc () { find "$NUTS_DIR_BAK" -maxdepth 1 -type f | head -n "$BACKUPS_TO_KEEP" | xargs --no-run-if-empty rm; }
+dl_file() {
+    local FILE_URL="$1"
+    local FILE_NAME
+	FILE_NAME="$(basename "$FILE_URL")"
+    local FILE_PATH="/tmp/$FILE_NAME"
+
+    if [ -f "$FILE_PATH" ]; then
+        rm "$FILE_PATH"
+    fi
+
+    if ! command -v axel >/dev/null 2>&1; then
+        return 1
+    fi
+
+    if ! curl --output /dev/null --silent --head --fail "$FILE_URL"; then
+        return 1
+    fi
+
+    axel -o "/tmp" -n 10 "$FILE_URL"
+
+    if [ $? -ne 0 ]; then
+        return 1
+    fi
+}
+
+
+bak_cc() {
+    if [ ! -d "$NUTS_DIR_BAK" ]; then
+        return 1
+    fi
+
+    if ! [[ "$BACKUPS_TO_KEEP" =~ ^[0-9]+$ ]]; then
+        return 1
+    fi
+
+    find "$NUTS_DIR_BAK" -maxdepth 1 -type f -exec rm {} +
+    find "$NUTS_DIR_BAK" -maxdepth 1 -type f | sort -r | tail -n +$((BACKUPS_TO_KEEP + 1)) | xargs --no-run-if-empty rm
+}
 
 
 # -- Mount the devices filesystem.
@@ -108,57 +167,70 @@ done
 # -- Create working directories in /home since this partition will likely have more space than the root partition, as set in our custom partition layout and the instructions on the website.
 
 if [[ ! -d "$NUTS_DIR_DLS" ]] && [[ ! -d "$NUTS_DIR_ISO" ]] && [[ ! -d "$NUTS_DIR_SQS" ]] && [[ ! -d "$NUTS_DIR_BAK" ]]; then
-	puts-info "Creating working directories, continuing..."
+	puts_info "Creating working directories, continuing..."
 	mkdir -p /home/.nuts/{backup,downloads,iso,squashfs}
 else
-	puts-info "Working directories exist, skipping..."
+	puts_info "Working directories exist, skipping..."
 fi
 
 
 # -- Run the backup cleaner.
 # -- Only keep the amount of backups defined in nuts.conf.
 
-puts-info "Cleaning older backups, continuing..."
+puts_info "Cleaning older backups, continuing..."
 bak_cc
 
 
 # -- Create the backup.
 # -- We assume that the /home partition is on an internal storage device (SATA or NVME), but one can never know, so run sync to flush the write cache.
 
-puts-info "Creating backup of ${CURRENT_DIST^n}, continuing..."
+puts_info "Creating backup of ${CURRENT_DIST^n}, continuing..."
 
-mksquashfs / "$NUTS_DIR_BAK"/nuts-backup-"$DATE_BACKUP_FILE".squashfs \
-	-e /boot/* \
-	-e /dev/* \
-	-ef /etc/shadow \
-	-e /home/ \
-	-e /proc/ \
-	-e /media/* \
-	-e /run/* \
-	-e /sys/* \
-	-e /tmp/* \
-	-e /var/{cache,lib,local,lock,log,mail,opt,run,spool,tmp}/ \
+BACKUP_FILE="$NUTS_DIR_BAK/nuts-backup-$DATE_BACKUP_FILE.squashfs"
+
+mksquashfs / "$BACKUP_FILE" \
+	-e '/boot/*' \
+	-e '/dev/*' \
+	-ef '/etc/shadow' \
+	-e '/home/' \
+	-e '/proc/' \
+	-e '/media/*' \
+	-e '/run/*' \
+	-e '/sys/*' \
+	-e '/tmp/*' \
+	-e '/var/{cache,lib,local,lock,log,mail,opt,run,spool,tmp}/' \
 	-comp zstd \
 	-Xcompression-level 22 \
 	-no-progress \
 	-b 1048576
-md5sum "$(echo "$NUTS_DIR_BAK"/nuts-backup-*.squashfs | tr ' ' '\n' | tail -n 1)" > "$NUTS_DIR_BAK"/nuts-backup.md5sum
+
+md5sum "$BACKUP_FILE" > "$NUTS_DIR_BAK/nuts-backup.md5sum"
+
 sync
 
-puts-success "Success! Backup has been created."
+puts_success "Success! Backup has been created."
 
 
 # -- This utility targets Nitrux version 2.8.0 and newer. However, aria2c is only included by default with version 2.9.0.
 # -- To use this utility in previous versions of Nitrux, we need to download a static binary.
 # -- So, first check if aria2c is available and download it if not.
 
-if [[ -f "/usr/bin/aria2c" ]]; then
-	puts-success "Success! aria2c binary is found, skipping..."
+ARIA2_BINARY="/usr/bin/aria2c"
+ARIA2_RELEASE_URL="https://github.com/abcfy2/aria2-static-build/releases/download/1.36.0/aria2-x86_64-linux-musl_static.zip"
+ARIA2_TEMP_DIR="/tmp/aria2-temp"
+
+if [[ -f "$ARIA2_BINARY" ]]; then
+    puts_success "Success! aria2c binary is found, skipping..."
 else
-	puts-info "Can't find aria2c binary, downloading..."
-	dl_file https://github.com/abcfy2/aria2-static-build/releases/download/1.36.0/aria2-x86_64-linux-musl_static.zip
-	puts-info "Adding aria2c static binary, continuing..."
-	unzip /tmp/aria2-x86_64-linux-musl_static.zip -d /usr/bin
+    puts_info "Can't find aria2c binary, downloading..."
+    dl_file "$ARIA2_RELEASE_URL"
+
+    puts_info "Adding aria2c static binary, continuing..."
+    mkdir -p "$ARIA2_TEMP_DIR"
+    unzip /tmp/aria2-x86_64-linux-musl_static.zip -d "$ARIA2_TEMP_DIR"
+    cp "$ARIA2_TEMP_DIR/aria2c" "$ARIA2_BINARY"
+
+    rm -rf "$ARIA2_TEMP_DIR"
 fi
 
 
@@ -168,40 +240,42 @@ fi
 # -- Use the magnet link from the query file.
 # -- Magnet link is provided by FOSS Torrents https://fosstorrents.com/distributions/nitrux/#downloads.
 
-if [[ -f "$NUTS_DIR_DLS/nitrux.iso" ]]; then
-	puts-info "ISO file found, skipping..."
+ISO_FILE="$NUTS_DIR_DLS/nitrux.iso"
+
+if [[ -f "$ISO_FILE" ]]; then
+    puts_info "ISO file found, skipping..."
 else
-	puts-info "ISO file not found! Dowloading ISO using aria2c, continuing..."
-	MAGNET_LINK="$(tail /tmp/nuts-query.info | grep magnetlink= | rev | cut -d '=' -f -42 | rev)"
-	aria2c -d "$NUTS_DIR_DLS" --log-level=warn --seed-time=0 "$MAGNET_LINK"
-	mv "$(echo "$NUTS_DIR_DLS"/nitrux-nx-desktop-plasma-*-amd64.iso | tr ' ' '\n' | tail -n 1)" "$NUTS_DIR_DLS"/nitrux.iso
+    puts_info "ISO file not found! Downloading ISO using aria2c, continuing..."
+    MAGNET_LINK=$(tail -n 1 /tmp/nuts-query.info | sed -n 's/.*magnetlink=\(.*\)/\1/p')
+    aria2c -d "$NUTS_DIR_DLS" --log-level=warn --seed-time=0 "$MAGNET_LINK"
+    mv "$NUTS_DIR_DLS"/nitrux-nx-desktop-plasma-*-amd64.iso "$ISO_FILE"
 fi
 
 
 # -- Verify the checksum of the ISO. Use the checksum from the query file.
 # -- Exit if checksum doesn't match.
 
-LOCAL_ISO_SUM="$(md5sum "$NUTS_DIR_DLS"/nitrux.iso | cut -c -32)"
-DL_ISO_SUM="$(tail /tmp/nuts-query.info | grep isosum= | cut -c -44 | rev | cut -c -32 | rev)"
+LOCAL_ISO_SUM=$(md5sum "$NUTS_DIR_DLS"/nitrux.iso | awk '{ print $1 }')
+DL_ISO_SUM=$(tail -n 1 /tmp/nuts-query.info | sed -n 's/.*isosum=\(.*\)/\1/p')
 
 if [[ "$LOCAL_ISO_SUM" == "$DL_ISO_SUM" ]]; then
-	puts-info "ISO checksum matches, continuing..."
+    puts_info "ISO checksum matches, continuing..."
 else
-	puts-error "ISO checksum does not match, quitting."
-	rm "$NUTS_DIR_DLS"/nitrux.iso
-	exit 1
+    puts_error "ISO checksum does not match, quitting."
+    rm "$NUTS_DIR_DLS"/nitrux.iso
+    exit 1
 fi
 
 
 # -- Mount the ISO and the SquashFS.
 
-mount "$NUTS_DIR_DLS"/nitrux.iso "$NUTS_DIR_ISO"
-mount "$NUTS_DIR_ISO"/casper/filesystem.squashfs "$NUTS_DIR_SQS"
+mount "$NUTS_DIR_DLS"/nitrux.iso "$NUTS_DIR_ISO" || { puts_error "Failed to mount ISO, quitting."; exit 1; }
+mount "$NUTS_DIR_ISO"/casper/filesystem.squashfs "$NUTS_DIR_SQS" || { puts_error "Failed to mount squashfs file, quitting."; exit 1; }
 
 
 # -- Now comes the good part; proceed with running rsync and update the current installation.
 
-puts-info "Updating ${CURRENT_DIST^n}, continuing..."
+puts_info "Updating ${CURRENT_DIST^n}, continuing..."
 
 dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/rsync-exclude.list
 
@@ -214,7 +288,7 @@ eval "$RSYNC_COMMAND"
 
 sync
 
-puts-success "Success! Update has been applied."
+puts_success "Success! Update has been applied."
 
 
 # -- Unmount the ISO and the SquashFS.
@@ -241,11 +315,20 @@ unmount_directory "/home"
 
 # -- Do a cleanup of the synced root.
 
-puts-info "Calling the $TOOL_NAME Cleanup Crew, continuing..."
+puts_info "Calling the $TOOL_NAME Cleanup Crew, continuing..."
 
-dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-cc
-dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-cc-file.list
-chmod +x /tmp/nuts-cc && bash /tmp/nuts-cc
+CLEANUP_SCRIPT_URL="https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-cc"
+FILE_LIST_URL="https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-cc-file.list"
+
+dl_file "$CLEANUP_SCRIPT_URL" || { puts_error "Failed to download the cleanup script, quitting."; exit 1; }
+dl_file "$FILE_LIST_URL" || { puts_error "Failed to download the file list, quitting."; exit 1; }
+
+if chmod +x /tmp/nuts-cc && bash /tmp/nuts-cc; then
+    puts_success "Cleanup script executed successfully."
+else
+    puts_error "Failed to execute the cleanup script, quitting."
+    exit 1
+fi
 
 
 # -- Update GRUB.
@@ -257,7 +340,7 @@ update-grub
 # -- Leave the Matri... I mean, the overlay.
 
 rm -r \
-	/tmp//nuts-cc
+	/tmp/nuts-cc
 
 exit
 
