add color to messages, add more messages

diff --git a/usr/bin/nuts b/usr/bin/nuts
--- a/usr/bin/nuts
+++ b/usr/bin/nuts
@@ -29,20 +29,31 @@
 set -e
 
 
-# -- Print messages to stdin.
+# -- Set program name and version.
 
-puts () { printf "\n\n --- %s\n" "$*"; }
+TOOL_NAME="Nitrux Update System Tool"
+TOOL_SHRT_NAME="nuts"
+TOOL_VERSION="$(md5sum /usr/bin/nuts | cut -c -32)"
+
+
+# -- Print informative messages to stdin.
+
+puts-info () { printf "$TOOL_SHRT_NAME: \e[34mInfo:\e[0m %b\n\n" "$*"; }
+
+
+# -- Print success messages to stdin.
+
+puts-success () { printf "$TOOL_SHRT_NAME: \e[32mSuccess:\e[0m %b\n\n" "$*"; }
+
+
+# -- Print error messages to stdin.
+
+puts-error () { printf "$TOOL_SHRT_NAME: \e[31mError:\e[0m %b\n\n" "$*"; }
 
 
 # -- Display an error when no flag is used.
 
-error () { printf "nuts: \e[31mError:\e[0m: %b\n" "$*" >&2; exit 1; }
-
-
-# -- Set program name and version.
-
-TOOL_NAME="Nitrux Update System Tool"
-TOOL_VERSION="$(md5sum /usr/bin/nuts | cut -c -32)"
+error () { printf "$TOOL_SHRT_NAME: \e[31mError:\e[0m %b\n\n" "$*" >&2; exit 1; }
 
 
 # -- Define the path of the nuts configuration file.
@@ -54,31 +65,23 @@ CONFIG_FILE="/etc/nuts.conf"
 # -- Include fix for SC1090 – ShellCheck.
 
 if [[ ! -f $CONFIG_FILE ]]; then
-    puts "Configuration file not found!, quitting." 2>&1
+    puts-error "$TOOL_NAME configuration file not found!, quitting." 2>&1
     exit 1
 else
-	puts "Success! Configuration file found, continuing..."
+	puts-success "Success! $TOOL_NAME configuration file found, continuing..."
 	# shellcheck source=/dev/null
 	. "$CONFIG_FILE"
 fi
-
-
-# -- Use a log file.
-# -- Everything below will go to the file nuts.log.
-
-exec 3>&1 4>&2
-trap 'exec 2>&4 1>&3' 0 1 2 3
-exec 1>"$NUTS_LOG" 2>&1
 
 
 # -- Check if this is running as root.
 # -- Exit if not running as root.
 
 if [ "$EUID" -ne 0 ]; then
-	puts "$TOOL_NAME is not running as root."
+	puts-error "$TOOL_NAME is not running as root, quitting."
 	exit 1
 else
-	puts "$TOOL_NAME is running as root."
+	puts-info "$TOOL_NAME is running as root, continuing..."
 	ROOT="sudo"
 fi
 
@@ -89,10 +92,18 @@ dl_file () { axel -a -o /tmp -n 10 "$@"; }
 overlay_ch () { $ROOT overlayroot-chroot; }
 
 
+# -- Use a log file.
+# -- Everything below will go to the file nuts.log.
+
+exec 3>&1 4>&2
+trap 'exec 2>&4 1>&3' 0 1 2 3
+exec 1>"$NUTS_LOG" 2>&1
+
+
 # -- Flag parsing.
 
 case "$1" in
-    ( -h | --help ) puts "$TOOL_NAME" \
+    ( -h | --help ) puts-info "$TOOL_NAME" \
 		"Description:" \
 		"    $TOOL_NAME or nuts is a utility to update the Nitrux Operating System and back up the root for rollbacks." \
 		"    ⚠️ Important: nuts is intended to work exclusively in Nitrux OS, and using this utility in other distributions will break them or not work at all." \
@@ -117,7 +128,7 @@ case "$1" in
 
 		exit;;
 
-    ( -v | --version )  puts "nuts: version $TOOL_VERSION." \
+    ( -v | --version )  puts-info "nuts: version $TOOL_VERSION." \
 		"The license used for this file and its contents is: BSD-3-Clause." \
 		"Authors:" \
 		"    Copyright <2023> <Uri Herrera <uri_herrera@nxos.org>>" \
@@ -145,9 +156,9 @@ case "$1" in
 		TARGET_DIST="nitrux"
 
 		if [ "$CURRENT_DIST" == "$TARGET_DIST" ]; then
-			puts "Success! This utility is running in ${TARGET_DIST^n}, continuing..."
+			puts-success "Success! This utility is running in ${TARGET_DIST^n}, continuing..."
 		else
-			puts "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^n}, and using this utility in ${CURRENT_DIST^} will break it and not work at all."
+			puts-error "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^n}, and using this utility in ${CURRENT_DIST^} will break it and not work at all. Quitting."
 			exit 1
 		fi
 
@@ -156,9 +167,9 @@ case "$1" in
 		# -- Exit if connection test fails.
 
 		if ping -q -c 1 -W 1 nxos.org >/dev/null; then
-			puts "Success! This computer can reach the internet, continuing..."
+			puts-success "Success! This computer can reach the internet, continuing..."
 		else
-			puts "This computer can't reach the internet, quitting."
+			puts-error "This computer can't reach the internet, quitting."
 			exit 1
 		fi
 
@@ -175,10 +186,10 @@ case "$1" in
 		NUTS_DIR_BAK="/home/.nuts/backup"
 
 		if [ ! -d "$NUTS_DIR_DLS" ] && [ ! -d "$NUTS_DIR_ISO" ] && [ ! -d "$NUTS_DIR_SQS" ] && [ ! -d "$NUTS_DIR_BAK" ]; then
-			puts "Creating working directories, continuing..."
+			puts-info "Creating working directories, continuing..."
 			$ROOT mkdir -p /home/.nuts/{iso,squashfs,backup}
 		else
-			puts "Working directories exist, skipping..."
+			puts-info "Working directories exist, skipping..."
 		fi
 
 
@@ -186,9 +197,9 @@ case "$1" in
 		# -- Exit if it doesn't.
 
 		if [ ! -f "/installed_pkgs_end.txt" ]; then
-			puts "Build list found, continuing..."
+			puts-info "Build list found, continuing..."
 		else
-			puts "Build list not found, quitting."
+			puts-error "Build list not found, quitting."
 			exit 1
 		fi
 
@@ -197,6 +208,7 @@ case "$1" in
 		# -- This file is always downloaded to a temporary directory, as there's no reason to keep it.
 
 		if [ ! -f "/tmp/nuts-query" ]; then
+			puts-info "Downloading nuts-query, continuing..."
 			dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-query.info
 		fi
 
@@ -210,10 +222,10 @@ case "$1" in
 		REMOTE_SUM="$(tail /tmp/nuts-query.info | grep rootlistsum= | cut -c -44 | rev | cut -c -32 | rev)"
 
 		if [ "$LOCAL_SUM" == "$REMOTE_SUM" ]; then
-			puts "The current installation of ${TARGET_DIST^n} is up to date."
+			puts-info "The current installation of ${TARGET_DIST^n} is up to date."
 			exit 0
 		else
-			puts "Preparing to update ${TARGET_DIST^n}, continuing..."
+			puts-info "Preparing to update ${TARGET_DIST^n}, continuing..."
 		fi
 
 
@@ -222,6 +234,8 @@ case "$1" in
 		# -- This process begins as a step before doing an update.
 		# -- Backup files are only generated when updating; the user can't ask the utility to create them on demand.
 		# -- We assume that the /home partition is on an internal storage device (SATA or NVME), but one can never know, so run sync to flush the write cache.
+
+		puts-info "Creating backup of ${CURRENT_DIST^n}, continuing..."
 
 		$ROOT mksquashfs / "$NUTS_DIR_BAK"/nuts-backup-"$DATE_BACKUP_FILE".squashfs \
 			-e /boot/* \
@@ -239,6 +253,8 @@ case "$1" in
 			-b 1048576
 		$ROOT md5sum "$(echo "$NUTS_DIR_BAK"/nuts-backup-*.squashfs | tr ' ' '\n' | tail -n 1)" > "$NUTS_DIR_BAK"/nuts-backup.md5sum
 		sync
+
+		puts-success "Success! Backup has been created."
 
 
 		# -- Step 2: Actual Update sub-process
@@ -259,9 +275,9 @@ case "$1" in
 		DL_ISO_SUM="$(tail /tmp/nuts-query.info | grep rootlistsum= | cut -c -44 | rev | cut -c -32 | rev)"
 
 		if [ "$LOCAL_ISO_SUM" == "$DL_ISO_SUM" ]; then
-			puts "ISO checksum matches, continuing..."
+			puts-info "ISO checksum matches, continuing..."
 		else
-			puts "ISO checksum does not match, quitting."
+			puts-error "ISO checksum does not match, quitting."
 			rm "$NUTS_DIR_DLS"/nitrux.iso
 			exit 1
 		fi
@@ -297,6 +313,8 @@ case "$1" in
 
 			# -- Now comes the good part; proceed with running rsync and update the current installation.
 
+			puts-info "Updating ${CURRENT_DIST^n}, continuing..."
+			
 			rsync -avzh \
 				--exclude /dev/ \
 				--exclude /etc/shadow \
@@ -308,6 +326,8 @@ case "$1" in
 				--progress \
 				"$NUTS_DIR_SQS" /
 			sync
+
+			puts-success "Success! Update has been applied."
 
 
 			# -- Unmount the ISO and the SquashFS.
@@ -328,6 +348,7 @@ case "$1" in
 
 			# -- Do a cleanup of the synced root.
 
+			puts-info "Calling the $TOOL_NAME Cleanup Crew, continuing..."
 			dl_file https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-cc
 			chmod +x /tmp//nuts-cc
 			bash /tmp//nuts-cc
@@ -360,9 +381,9 @@ case "$1" in
 		GEN_BAK_SUM="$(tail "$NUTS_DIR_BAK"/nuts-backup.md5sum | cut -c -32)"
 
 		if [ "$BACKUP_SUM" == "$GEN_BAK_SUM" ]; then
-			puts "Backup checksum matches, continuing..."
+			puts-info "Backup checksum matches, continuing..."
 		else
-			puts "Backup checksum does not match, quitting."
+			puts-error "Backup checksum does not match, quitting."
 			exit 1
 		fi
 
@@ -393,6 +414,8 @@ case "$1" in
 
 			# -- Now comes the good part; proceed with running rsync and restore the backup.
 
+			puts-info "Restoring backup of ${CURRENT_DIST^n}, continuing..."
+
 			rsync -avzh \
 				--exclude /dev/ \
 				--exclude /etc/shadow \
@@ -404,6 +427,8 @@ case "$1" in
 				--progress \
 				"$NUTS_DIR_SQS" /
 			sync
+
+			puts-success "Success! Backup has been restored."
 
 
 			# -- Unmount the SquashFS.
