refactor code
- use a backup sqs from a newer installation in the same way a sqs is used for restore
- this is for #6 since seemingly, using the sqs from an ISO somehow brakes the wayland session; however, upong updating and restoring the root backup the session works

diff --git a/usr/bin/nuts b/usr/bin/nuts
--- a/usr/bin/nuts
+++ b/usr/bin/nuts
@@ -216,9 +216,10 @@ for cmd; do
 				"    -d or --debug        Enable verbose output." \
 				"" \
 				"Operations:" \
-				"    update       Update the currently installed root using the media specified in nuts-query and creates a backup of the current root directory." \
-				"    restore      Restore the backup of the root directory generated during the update." \
-				"    rescue       Restore the backup of the root partition in case of an interrupted update.." \
+				"    update            Update the currently installed root using the media specified in nuts-query and creates a backup of the current root directory." \
+				"    restore           Restore the backup of the root directory generated during the update." \
+				"    rescue            Restore the backup of the root partition in case of an interrupted update." \
+				"    self-update       Update $TOOL_NAME and its configuration file using the default branch set in the configuration file." \
 				"" \
 				"Usage:" \
 				"    sudo nuts <flag> (operation)" \
@@ -336,28 +337,27 @@ done
 			# -- Create the directories for nuts.
 			# -- Create working directories in /home since this partition will likely have more space than the root partition.
 
-			DIRECTORIES=("$NUTS_DIR_BAK" "$NUTS_DIR_XFS" "$NUTS_DIR_ISO" "$NUTS_DIR_DLS" "$NUTS_DIR_SQS")
+			DIRECTORIES=("$NUTS_DIR_BAK" "$NUTS_DIR_XFS" "$NUTS_DIR_DLS" "$NUTS_DIR_SQS")
 
 			for DIR in "${DIRECTORIES[@]}"; do
 			if [[ ! -d "$DIR" ]]; then
 				puts_error "Directory '$DIR' does not exist. Creating the directory..."
 				if ! mkdir -p "$DIR"; then
-				puts_error "Failed to create directory '$DIR'. Exiting..."
+				puts_error "Failed to create directory '$DIR', quitting..."
 				exit 1
 				fi
 				puts_info "Directory '$DIR' created successfully."
 			fi
 			done
 
-			puts_info "All required directories exist. Continuing."
+			puts_info "All required directories exist, continuing..."
 
 
 			# -- Step 1: Backup sub-process
 
 			# -- This process begins as a step before doing an update.
 			# -- Backup files are only generated when updating; the user can't ask the utility to create them on demand.
-			# -- This process is done inside the chroot; otherwise, when using overlayroot-chroot, the files, and paths will not exist.
-
+			# -- This utility will create two backups for redundancy, first a backup of the root partition and then a backup of the root directory.
 
 			# -- Create a backup of the partition for redundancy using xfsdump to later use it during a rescue operation from a Live session.
 			# -- By the way, only *one* backup file is created, then compress the backup file using zstd. We must delete the original file after compression.
@@ -379,7 +379,7 @@ done
 				rm -f "$XFS_BACKUP_FILE"
 				md5sum "$COMPRESSED_XFS_BACKUP" > "$NUTS_DIR_XFS/xfs-backup.md5sum"
 				sync
-				puts_success "Success! $ROOT_PARTITION_LABEL redundant backup has been created."
+				puts_success "Success! $ROOT_PARTITION_LABEL redundant backup has been created, continuing..."
 			fi
 
 
@@ -423,6 +423,43 @@ done
 
 			# -- The restore process is the same as the Actual Update sub-process but using the backup SquashFS.
 
+			# -- Ensure that this utility runs in Nitrux and has an Internet connection.
+			# -- Exit if value is not 'nitrux'.
+
+			if [[ "$CURRENT_DIST" == "$TARGET_DIST" ]]; then
+				puts_success "This utility is running in ${TARGET_DIST^}. Continuing..."
+			else
+				puts_error "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^}. Using this utility in ${CURRENT_DIST^} will break it and not work at all. Quitting."
+				exit 1
+			fi
+
+
+			# -- Check Internet connection but do nothing yet.
+			# -- For some reason, ping fails in GNOME Boxes even though ping works literally everywhere else. Use wget as an alternative to verify a connection.
+			# -- Exit if connection test fails.
+
+			if ping -q -c 1 -W 1 nxos.org >/dev/null && ping -q -c 1 -W 1 github.com >/dev/null || wget -q --spider https://filesamples.com/samples/document/txt/sample1.txt; then
+				puts_success "This computer can reach the Internet. Continuing..."
+			else
+				puts_error "This computer cannot reach the Internet. Quitting."
+				exit 1
+			fi
+
+
+			# -- This process is also done inside the chroot and it is the same as Calamares, except for user creation, mounts and bootloader configuration.
+			# -- After using overlay_ch, it's essential to remember that **EVERY COMMAND IS RUNNING AS ROOT AND ON THE LOWER DIRECTORY OF THE OVERLAY**.
+
+
+			OVERLAYROOT="/usr/sbin/overlayroot-chroot"
+
+			if [[ ! -f "$OVERLAYROOT" ]]; then
+				puts_error "Can't find overlayroot, quitting."
+				exit 1
+			else
+				puts_info "Found overlayroot, continuing..."
+			fi
+
+
 			# -- Enter the Matri... I mean, the overlay.
 			# -- Run nuts-crr to perform the restore actions inside the chroot.
 			# -- Always download the latest component. The component will remain in the filesystem after using it; however, once the user executes this <operation> again, it will be deleted and re-downloaded.
@@ -446,13 +483,24 @@ done
 
 			# -- The Rescue Process is a special handling of an unforeseen event; as such, this <operation> does not require using overlayroot-chroot.
 
+			# -- Ensure that this utility runs in Nitrux and has an Internet connection.
+			# -- Exit if value is not 'nitrux'.
+
+			if [[ "$CURRENT_DIST" == "$TARGET_DIST" ]]; then
+				puts_success "This utility is running in ${TARGET_DIST^}. Continuing..."
+			else
+				puts_error "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^}. Using this utility in ${CURRENT_DIST^} will break it and not work at all. Quitting."
+				exit 1
+			fi
+
+
 			# -- We do this because if, during the Actual Update sub-process with rsync, rsync is interrupted, the root will be in an inconsistent state.
 			# -- That means the root is unusable, i.e., the user can't access the GUI or, worse, a TTY, so the user can't restore the SquashFS.
 			# -- With that being the case, this <operation> allows the user to restore the root partition from a Live session.
 
 			# -- Automatically check if this utility is running in a Live session. Calamares is an easy check as it's only available in a Live session.
 			# -- This check assumes that the root is now inconsistent; thus, using the SquashFS backup is impossible, so we must restore the XFS backup hence why the user tells this utility to restore a backup from a Live session.
-			# -- If the check returns that this utility is not running from a Live session, and direct the user to use the SquashFS backup instead.
+			# -- If the check returns that this utility is not running from a Live session, it directs the user to use the SquashFS backup instead.
 
 			ROOT_PARTITION=$(findfs LABEL=NX_ROOT)
 			ROOT_PARTITION_LABEL=$(blkid -o value -s LABEL "$ROOT_PARTITION")
@@ -534,11 +582,48 @@ done
 
 			# -- Step Y: Self-Update Process
 
-			# -- Whenever a new update to the utility is uploaded to the repository, users use this <operation> to update nuts.
-			# -- This also updates the configuration file, so.
+			# -- Ensure that this utility runs in Nitrux and has an Internet connection.
+			# -- Exit if value is not 'nitrux'.
 
-			overlay_ch rm -f /usr/bin/nuts-sup >"$OUTPUT_FILE" 2>&1
-			overlay_ch axel -o /usr/bin -c -n 10 "https://raw.githubusercontent.com/Nitrux/nuts/$NUTS_BRANCH/usr/bin/nuts-sup" >"$OUTPUT_FILE" 2>&1
+			if [[ "$CURRENT_DIST" == "$TARGET_DIST" ]]; then
+				puts_success "This utility is running in ${TARGET_DIST^}. Continuing..."
+			else
+				puts_error "$TOOL_NAME is intended to work exclusively in ${TARGET_DIST^}. Using this utility in ${CURRENT_DIST^} will break it and not work at all. Quitting."
+				exit 1
+			fi
+
+			# -- Check Internet connection but do nothing yet.
+			# -- For some reason, ping fails in GNOME Boxes even though ping works literally everywhere else. Use wget as an alternative to verify a connection.
+			# -- Exit if connection test fails.
+
+			if ping -q -c 1 -W 1 nxos.org >/dev/null && ping -q -c 1 -W 1 github.com >/dev/null || wget -q --spider https://filesamples.com/samples/document/txt/sample1.txt; then
+				puts_success "This computer can reach the Internet. Continuing..."
+			else
+				puts_error "This computer cannot reach the Internet. Quitting."
+				exit 1
+			fi
+
+
+			# -- This process is also done inside the chroot and it is the same as Calamares, except for user creation, mounts and bootloader configuration.
+			# -- After using overlay_ch, it's essential to remember that **EVERY COMMAND IS RUNNING AS ROOT AND ON THE LOWER DIRECTORY OF THE OVERLAY**.
+
+
+			OVERLAYROOT="/usr/sbin/overlayroot-chroot"
+
+			if [[ ! -f "$OVERLAYROOT" ]]; then
+				puts_error "Can't find overlayroot, quitting."
+				exit 1
+			else
+				puts_info "Found overlayroot, continuing..."
+			fi
+
+
+			# -- Whenever a new update to the utility is uploaded to the repository, users use this <operation> to update nuts.
+			# -- This also updates the configuration file.
+			# -- Always download the latest component. The component will remain in the filesystem after using it; however, once the user executes this <operation> again, it will be deleted and re-downloaded.
+
+			overlay_ch find /usr/bin -type f -name "nuts-sup" -exec rm {} \; >"$OUTPUT_FILE" 2>&1
+			overlay_ch axel -o /usr/bin -c -n 10 "https://raw.githubusercontent.com/Nitrux/nuts/$NUTS_BRANCH/tmp/nuts-sup" >"$OUTPUT_FILE" 2>&1
 			overlay_ch chmod +x /usr/bin/nuts-sup >"$OUTPUT_FILE" 2>&1
 			overlay_ch nuts-sup
 
