[ci skip] also cleanup on restore

diff --git a/usr/bin/nuts-crr b/usr/bin/nuts-crr
--- a/usr/bin/nuts-crr
+++ b/usr/bin/nuts-crr
@@ -201,6 +201,24 @@ sync
 puts_success "Success! Backup has been restored."
 
 
+# -- Do a cleanup of the synced root.
+
+puts_info "Calling the $TOOL_NAME Cleanup Crew, continuing..."
+
+CLEANUP_SCRIPT_URL="https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-ccr"
+FILE_LIST_URL="https://raw.githubusercontent.com/Nitrux/nuts/main/tmp/nuts-ccr-file.list"
+
+dl_file "$CLEANUP_SCRIPT_URL" || { puts_error "Failed to download the cleanup script, quitting."; exit 1; }
+dl_file "$FILE_LIST_URL" || { puts_error "Failed to download the file list, quitting."; exit 1; }
+
+if chmod +x /tmp/nuts-ccr && bash /tmp/nuts-ccr; then
+    puts_success "Cleanup script executed successfully."
+else
+    puts_error "Something failed in the cleanup script, quitting."
+    exit 1
+fi
+
+
 # -- Update GRUB.
 
 update-grub
@@ -230,6 +248,9 @@ sync
 
 # -- Finalizing.
 # -- Leave the Matri... I mean, the overlay.
+
+rm -r \
+	/tmp/nuts-ccr
 
 exit
 
